# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1029, 881)
        MainWindow.setStyleSheet("background:rgba(86, 86, 86, 200)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Misc Fixed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Misc Fixed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(270, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background:rgba(255, 92, 16, 30)")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(0, 32))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 32))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_status_port1 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_status_port1.setFont(font)
        self.label_status_port1.setObjectName("label_status_port1")
        self.gridLayout.addWidget(self.label_status_port1, 0, 1, 1, 1)
        self.label_status_port2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_status_port2.setFont(font)
        self.label_status_port2.setObjectName("label_status_port2")
        self.gridLayout.addWidget(self.label_status_port2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(0, 32))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 32))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.label_status_port4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_status_port4.setFont(font)
        self.label_status_port4.setObjectName("label_status_port4")
        self.gridLayout.addWidget(self.label_status_port4, 3, 1, 1, 1)
        self.label_status_port3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_status_port3.setFont(font)
        self.label_status_port3.setObjectName("label_status_port3")
        self.gridLayout.addWidget(self.label_status_port3, 2, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(270, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("background:rgba(255, 92, 16, 30)")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton.setStyleSheet("background:rgba(255, 92, 16, 100)")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background:rgba(255, 92, 16, 100)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_3.setStyleSheet("background:rgba(255, 92, 16, 100)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_4.setStyleSheet("background:rgba(255, 92, 16, 100)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_5.setStyleSheet("background:rgba(255, 92, 16, 100)")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_6.setStyleSheet("background:rgba(255, 92, 16, 100)")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_5.addWidget(self.pushButton_6, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 3, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_7.setStyleSheet("background:rgba(255, 92, 16, 100)")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_5.addWidget(self.pushButton_7, 3, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_8.setStyleSheet("background:rgba(255, 92, 16, 100)")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_5.addWidget(self.pushButton_8, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_6.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("background:rgba(169, 230, 255, 40)")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 2)
        self.spinBoxOn_logic_1 = QtWidgets.QSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxOn_logic_1.sizePolicy().hasHeightForWidth())
        self.spinBoxOn_logic_1.setSizePolicy(sizePolicy)
        self.spinBoxOn_logic_1.setObjectName("spinBoxOn_logic_1")
        self.gridLayout_4.addWidget(self.spinBoxOn_logic_1, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 3, 1, 1)
        self.spinBoxOff_logic_1 = QtWidgets.QSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxOff_logic_1.sizePolicy().hasHeightForWidth())
        self.spinBoxOff_logic_1.setSizePolicy(sizePolicy)
        self.spinBoxOff_logic_1.setObjectName("spinBoxOff_logic_1")
        self.gridLayout_4.addWidget(self.spinBoxOff_logic_1, 0, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 2)
        self.spinBoxOn_logic_2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxOn_logic_2.setObjectName("spinBoxOn_logic_2")
        self.gridLayout_4.addWidget(self.spinBoxOn_logic_2, 1, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 3, 1, 1)
        self.spinBoxOff_logic_2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxOff_logic_2.setObjectName("spinBoxOff_logic_2")
        self.gridLayout_4.addWidget(self.spinBoxOff_logic_2, 1, 4, 1, 1)
        self.pushButton_logic_on = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_logic_on.sizePolicy().hasHeightForWidth())
        self.pushButton_logic_on.setSizePolicy(sizePolicy)
        self.pushButton_logic_on.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_logic_on.setStyleSheet("background:rgba(169, 230, 255, 170)")
        self.pushButton_logic_on.setObjectName("pushButton_logic_on")
        self.gridLayout_4.addWidget(self.pushButton_logic_on, 2, 0, 1, 1)
        self.label__status_logic = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label__status_logic.setFont(font)
        self.label__status_logic.setObjectName("label__status_logic")
        self.gridLayout_4.addWidget(self.label__status_logic, 4, 0, 1, 1)
        self.pushButton_logic_off = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_logic_off.sizePolicy().hasHeightForWidth())
        self.pushButton_logic_off.setSizePolicy(sizePolicy)
        self.pushButton_logic_off.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_logic_off.setStyleSheet("background:rgba(169, 230, 255, 170)")
        self.pushButton_logic_off.setObjectName("pushButton_logic_off")
        self.gridLayout_4.addWidget(self.pushButton_logic_off, 3, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_4.addWidget(self.checkBox_5, 0, 5, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_4.addWidget(self.checkBox_6, 1, 5, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(270, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background:rgba(137, 255, 64, 20)")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.midtemp = QtWidgets.QSpinBox(self.groupBox_2)
        self.midtemp.setObjectName("midtemp")
        self.gridLayout_2.addWidget(self.midtemp, 2, 1, 1, 1)
        self.temp2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.temp2.setObjectName("temp2")
        self.gridLayout_2.addWidget(self.temp2, 1, 1, 1, 1)
        self.temp1 = QtWidgets.QSpinBox(self.groupBox_2)
        self.temp1.setObjectName("temp1")
        self.gridLayout_2.addWidget(self.temp1, 0, 1, 1, 1)
        self.gigrom = QtWidgets.QSpinBox(self.groupBox_2)
        self.gigrom.setObjectName("gigrom")
        self.gridLayout_2.addWidget(self.gigrom, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("background:rgba(169, 230, 255, 40)")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.groupBox_3)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout_7.addWidget(self.timeEdit_2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(50, 0))
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 0, 0, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox_3)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_7.addWidget(self.timeEdit, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_7.addWidget(self.checkBox, 0, 4, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_7, 0, 0, 1, 2)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(50, 0))
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 0, 0, 1, 1)
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.groupBox_3)
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.gridLayout_8.addWidget(self.timeEdit_3, 0, 1, 1, 1)
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.groupBox_3)
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.gridLayout_8.addWidget(self.timeEdit_4, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 0, 3, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_8.addWidget(self.checkBox_2, 0, 4, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_8, 1, 0, 1, 2)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.timeEdit_7 = QtWidgets.QTimeEdit(self.groupBox_3)
        self.timeEdit_7.setObjectName("timeEdit_7")
        self.gridLayout_11.addWidget(self.timeEdit_7, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem5, 0, 3, 1, 1)
        self.timeEdit_8 = QtWidgets.QTimeEdit(self.groupBox_3)
        self.timeEdit_8.setObjectName("timeEdit_8")
        self.gridLayout_11.addWidget(self.timeEdit_8, 0, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(50, 0))
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 0, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_11.addWidget(self.checkBox_3, 0, 4, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 2, 0, 1, 2)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.timeEdit_6 = QtWidgets.QTimeEdit(self.groupBox_3)
        self.timeEdit_6.setObjectName("timeEdit_6")
        self.gridLayout_10.addWidget(self.timeEdit_6, 0, 2, 1, 1)
        self.timeEdit_5 = QtWidgets.QTimeEdit(self.groupBox_3)
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.gridLayout_10.addWidget(self.timeEdit_5, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(50, 0))
        self.label_21.setObjectName("label_21")
        self.gridLayout_10.addWidget(self.label_21, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 0, 3, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_10.addWidget(self.checkBox_4, 0, 4, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10, 3, 0, 1, 2)
        self.pushButton_logicTimer_on = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_logicTimer_on.sizePolicy().hasHeightForWidth())
        self.pushButton_logicTimer_on.setSizePolicy(sizePolicy)
        self.pushButton_logicTimer_on.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_logicTimer_on.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_logicTimer_on.setStyleSheet("background:rgba(169, 230, 255, 170)")
        self.pushButton_logicTimer_on.setObjectName("pushButton_logicTimer_on")
        self.gridLayout_12.addWidget(self.pushButton_logicTimer_on, 4, 0, 1, 1)
        self.pushButton_logicTimer_off = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_logicTimer_off.sizePolicy().hasHeightForWidth())
        self.pushButton_logicTimer_off.setSizePolicy(sizePolicy)
        self.pushButton_logicTimer_off.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_logicTimer_off.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_logicTimer_off.setStyleSheet("background:rgba(169, 230, 255, 170)")
        self.pushButton_logicTimer_off.setObjectName("pushButton_logicTimer_off")
        self.gridLayout_12.addWidget(self.pushButton_logicTimer_off, 5, 0, 1, 1)
        self.label_time_status = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_time_status.setFont(font)
        self.label_time_status.setObjectName("label_time_status")
        self.gridLayout_12.addWidget(self.label_time_status, 6, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem7, 7, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1029, 30))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Uptime:"))
        self.label_6.setText(_translate("MainWindow", "Time:"))
        self.groupBox.setTitle(_translate("MainWindow", "Status Buttons"))
        self.label_3.setText(_translate("MainWindow", "Порт № 2"))
        self.label_2.setText(_translate("MainWindow", "Порт № 1"))
        self.label_status_port1.setText(_translate("MainWindow", "OFF"))
        self.label_status_port2.setText(_translate("MainWindow", "OFF"))
        self.label_4.setText(_translate("MainWindow", "Порт № 3"))
        self.label_5.setText(_translate("MainWindow", "Порт № 4"))
        self.label_status_port4.setText(_translate("MainWindow", "OFF"))
        self.label_status_port3.setText(_translate("MainWindow", "OFF"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Port switcher"))
        self.label_16.setText(_translate("MainWindow", "Порт № 1"))
        self.pushButton.setText(_translate("MainWindow", "ON"))
        self.pushButton_2.setText(_translate("MainWindow", "OFF"))
        self.label_17.setText(_translate("MainWindow", "Порт № 2"))
        self.pushButton_3.setText(_translate("MainWindow", "ON"))
        self.pushButton_4.setText(_translate("MainWindow", "OFF"))
        self.label_18.setText(_translate("MainWindow", "Порт № 3"))
        self.pushButton_5.setText(_translate("MainWindow", "ON"))
        self.pushButton_6.setText(_translate("MainWindow", "OFF"))
        self.label_19.setText(_translate("MainWindow", "Порт № 4"))
        self.pushButton_7.setText(_translate("MainWindow", "ON"))
        self.pushButton_8.setText(_translate("MainWindow", "OFF"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Devices Logic"))
        self.label_12.setText(_translate("MainWindow", "Вкл Порт № 1 если меньше"))
        self.label_13.setText(_translate("MainWindow", "Выкл Порт № 1 больше"))
        self.label_14.setText(_translate("MainWindow", "Вкл Порт № 4 если меньше"))
        self.label_15.setText(_translate("MainWindow", "Выкл Порт № 4 больше"))
        self.pushButton_logic_on.setText(_translate("MainWindow", "Logic ON"))
        self.label__status_logic.setText(_translate("MainWindow", "Status devices logic"))
        self.pushButton_logic_off.setText(_translate("MainWindow", "Logic OFF"))
        self.checkBox_5.setText(_translate("MainWindow", "on / off"))
        self.checkBox_6.setText(_translate("MainWindow", "on / off"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Status Devices"))
        self.label_7.setText(_translate("MainWindow", "Температура_1"))
        self.label_8.setText(_translate("MainWindow", "Температура_2"))
        self.label_9.setText(_translate("MainWindow", "Свободный датчик"))
        self.label_11.setText(_translate("MainWindow", "Средняя температура"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Time logic"))
        self.label_10.setText(_translate("MainWindow", "Днат"))
        self.checkBox.setText(_translate("MainWindow", "on / off"))
        self.label_20.setText(_translate("MainWindow", "Мотор"))
        self.checkBox_2.setText(_translate("MainWindow", "on / off"))
        self.label_22.setText(_translate("MainWindow", "Приток"))
        self.checkBox_3.setText(_translate("MainWindow", "on / off"))
        self.label_21.setText(_translate("MainWindow", "Вентеляторы"))
        self.checkBox_4.setText(_translate("MainWindow", "on / off"))
        self.pushButton_logicTimer_on.setText(_translate("MainWindow", "Logic ON"))
        self.pushButton_logicTimer_off.setText(_translate("MainWindow", "Logic OFF"))
        self.label_time_status.setText(_translate("MainWindow", "Status time logic"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.menu_2.setTitle(_translate("MainWindow", "О программе"))
        self.action.setText(_translate("MainWindow", "Выход"))

